### ISSUE TITLE
Klient ska kunna lägga till kontakter

### ISSUE THREAD

**Issue by PhilipHolmqvist** [KeffaKlumpen/DA343A_UP_19#2]
En klient ska kunna lägga till en uppkopplad användare till Kontakter. Kontakter 
ska sparas på hårddisken (hos servern) då klienten avslutas och läsas in och visas i applikationen 
då den startats. Då användaren förbereder att skicka ett meddelande ska man 
kunna välja mottagare dels från kontakter och dels från uppkopplade användare.

**Comment by KeffaKlumpen** [comment]
Placeholder version fungerar, använder sig av en Hashtable<User, User[]>..

Behöver sparas till en fil vid server ändringar, och läsas från vid server start!

**Comment by KeffaKlumpen** [comment]
Kontakter sparas nu lokalt på servern (+ hämtas vid start)
.dat filen skapas dock inte automatiskt än..

**Comment by KeffaKlumpen** [comment]
data folder skapas automatiskt
contactLists.dat skapas automatiskt
