### ISSUE TITLE
Logga ALL trafik till filer på hårddisken

### ISSUE THREAD

**Issue by JSGHagman** [KeffaKlumpen/DA343A_UP_19#7]

**Comment by JSGHagman** [comment]
- SKAPA LOGGERKLASS
- SKAPA NY TEXTFIL (DÖPS EFTER DATUM) 
- LOGGA TRAFIK SOM FORMATTERADE STRÄNGAR

**Comment by KeffaKlumpen** [comment]
Log fil exempel:

20220103-0821_20220103-1230.txt

Uppdatera suffix vid varje redigering.

**Comment by KeffaKlumpen** [comment]
Logger class skapad. Behöver lägga till Logger.log() överallt där vi behöver det..

**Comment by KeffaKlumpen** [comment]
Vi ska logga all trafik till och från servern, inte klar

**Comment by PhilipHolmqvist** [comment]
Vad mer ska den logga?

**Comment by KeffaKlumpen** [comment]
Allt i ClientConnection.Output och Input liksom (kanske skippa ping-meddelanden..)

**Comment by KeffaKlumpen** [comment]
Färdig
